username = "u896388463_7vUOh"
password = "wInSTx5V149^"
host = "axstest.com"
port = 3306
database = "u896388463_a3uoA"
booking_table = "wp_amelia_customer_bookings"
users_table = "wp_amelia_users"
[theme]
primaryColor = "#1DB954"  # Customize primary color as needed
backgroundColor = "#0e1117"  # Dark background color
secondaryBackgroundColor = "#262730"
textColor = "#FFFFFF"
font = "sans serif"
base = "dark"  # Force dark mode